export const associationConstants = {

    UPDATE_ASSOCIATION_MODAL_FIELDS: 'UPDATE_ASSOCIATION_FIELDS',
    UPDATE_DELETE_ASSOCIATION_MODAL_FIELDS: 'UPDATE_DELETE_ASSOCIATION_MODAL_FIELDS',

    CREATE_ASSOCIATION_REQUEST:'CREATE_ASSOCIATION_REQUEST',
    CREATE_ASSOCIATION_SUCCESS: 'CREATE_ASSOCIATION_SUCCESS',
    CREATE_ASSOCIATION_FAILURE:'CREATE_ASSOCIATION_FAILURE',

    DELETE_ASSOCIATION_REQUEST: 'DELETE_ASSOCIATION_REQUEST',
    DELETE_ASSOCIATION_SUCCESS: 'DELETE_ASSOCIATION_SUCCESS',
    DELETE_ASSOCIATION_FAILURE: 'DELETE_ASSOCIATION_FAILURE',

    UPDATE_ASSOCIATION_REQUEST: 'UPDATE_ASSOCIATION_REQUEST',
    UPDATE_ASSOCIATION_SUCCESS: 'UPDATE_ASSOCIATION_SUCCESS',
    UPDATE_ASSOCIATION_FAILURE: 'UPDATE_ASSOCIATION_FAILURE',

    GET_ASSOCIATION_BY_ID_REQUEST: 'GET_ASSOCIATION_BY_ID_REQUEST',
    GET_ASSOCIATION_BY_ID_SUCCESS: 'GET_ASSOCIATION_BY_ID_SUCCESS',
    GET_ASSOCIATION_BY_ID_FAILURE: 'GET_ASSOCIATION_BY_ID_FAILURE',

    OPEN_ASSOCIATION_MODAL_REQUEST: 'OPEN_ASSOCIATION_MODAL_REQUEST',
    CLOSE_ASSOCIATION_MODAL_REQUEST: 'CLOSE_ASSOCIATION_MODAL_REQUEST',

    OPEN_ASSOCIATION_DELETE_MODAL_REQUEST: 'OPEN_ASSOCIATION_DELETE_MODAL_REQUEST',
    CLOSE_ASSOCIATION_DELETE_MODAL_REQUEST: 'CLOSE_ASSOCIATION_DELETE_MODAL_REQUEST',

    CLOSE_OPERATION_SUCCESS_MODAL: 'CLOSE_OPERATION_SUCCESS_MODAL',
    CLOSE_OPERATION_FAILED_MODAL: 'CLOSE_OPERATION_FAILED_MODAL',

    GET_ALL_ASSOCIATIONS_REQUEST: 'GET_ALL_ASSOCIATIONS_REQUEST',
    GET_ALL_ASSOCIATIONS_SUCCESS: 'GET_ALL_ASSOCIATIONS_SUCCESS',
    GET_ALL_ASSOCIATIONS_FAILURE:  'GET_ALL_ASSOCIATIONS_FAILURE',

    CLEAR_ASSOCIATION:'CLEAR_ASSOCIATION'



};

export * from './associationConstants'