export const associationTypeConstants = {
    GET_ALL_ASSOCIATION_TYPES_REQUEST: "GET_ALL_ASSOCIATION_TYPES_REQUEST",
    GET_ALL_ASSOCIATION_TYPES_SUCCESS: "GET_ALL_ASSOCIATION_TYPES_SUCCESS",
    GET_ALL_ASSOCIATION_TYPES_FAILURE: "GET_ALL_ASSOCIATION_TYPES_FAILURE",

    GET_ASSOCIATION_TYPE_BY_ID_REQUEST: 'GET_ASSOCIATION_TYPE_BY_ID_REQUEST',
    GET_ASSOCIATION_TYPE_BY_ID_SUCCESS: 'GET_ASSOCIATION_TYPE_BY_ID_SUCCESS',
    GET_ASSOCIATION_TYPE_BY_ID_FAILURE: 'GET_ASSOCIATION_TYPE_BY_ID_FAILURE',

    SAVE_ALL_ASSOCIATION_TYPES_REQUEST: 'SAVE_ALL_ASSOCIATION_TYPES_REQUEST',
    SAVE_ALL_ASSOCIATION_TYPES_SUCCESS: 'SAVE_ALL_ASSOCIATION_TYPES_SUCCESS',
    SAVE_ALL_ASSOCIATION_TYPES_FAILURE: 'SAVE_ALL_ASSOCIATION_TYPES_FAILURE',

    SAVE_ASSOCIATION_TYPES_REQUEST: 'SAVE_ASSOCIATION_TYPES_REQUEST',
    SAVE_ASSOCIATION_TYPES_SUCCESS: 'SAVE_ASSOCIATION_TYPES_SUCCESS',
    SAVE_ASSOCIATION_TYPES_FAILURE: 'SAVE_ASSOCIATION_TYPES_FAILURE',

    CREATE_ASSOCIATION_TYPES_REQUEST: "CREATE_ASSOCIATION_TYPES_REQUEST",
    CREATE_ASSOCIATION_TYPES_SUCCESS: "CREATE_ASSOCIATION_TYPES_SUCCESS",
    CREATE_ASSOCIATION_TYPES_FAILURE: "CREATE_ASSOCIATION_TYPES_FAILURE",

    DELETE_ASSOCIATION_TYPES_REQUEST: "DELETE_ASSOCIATION_TYPES_REQUEST",
    DELETE_ASSOCIATION_TYPES_SUCCESS: "DELETE_ASSOCIATION_TYPES_SUCCESS",
    DELETE_ASSOCIATION_TYPES_FAILURE: "DELETE_ASSOCIATION_TYPES_FAILURE",

    UPDATE_ASSOCIATION_TYPES_REQUEST: "UPDATE_ASSOCIATION_TYPES_REQUEST",
    UPDATE_ASSOCIATION_TYPES_SUCCESS: "UPDATE_ASSOCIATION_TYPES_SUCCESS",
    UPDATE_ASSOCIATION_TYPES_FAILURE: "UPDATE_ASSOCIATION_TYPES_FAILURE",


    UPDATE_ASSOCIATION_TYPE_ROLE_TOPIC_TYPE_REQUEST:'UPDATE_ASSOCIATION_TYPE_ROLE_TOPIC_TYPE_REQUEST',
    UPDATE_ASSOCIATION_TYPE_ROLE_TOPIC_TYPE_SUCCESS:'UPDATE_ASSOCIATION_TYPE_ROLE_TOPIC_TYPE_SUCCESS',
    UPDATE_ASSOCIATION_TYPE_ROLE_TOPIC_TYPE_FAILURE: 'UPDATE_ASSOCIATION_TYPE_ROLE_TOPIC_TYPE_FAILURE',

    UPDATE_ASSOCIATION_TYPE_FIELD : 'UPDATE_ASSOCIATION_TYPE_FIELD',
    UPDATE_ASSOCIATION_TYPE_ROLE_TOPIC_TYPE_FIELD:'UPDATE_ASSOCIATION_TYPE_ROLE_TOPIC_TYPE_FIELD',

    OPEN_ASSOCIATION_TYPES_MODAL_REQUEST: 'OPEN_ASSOCIATION_TYPES_MODAL_REQUEST',
    CLOSE_ASSOCIATION_TYPES_MODAL_REQUEST: 'CLOSE_ASSOCIATION_TYPES_MODAL_REQUEST',

    OPEN_ASSOCIATION_TYPES_DELETE_CONFIRM: 'OPEN_ASSOCIATION_TYPES_DELETE_CONFIRM',
    CLOSE_ASSOCIATION_TYPES_DELETE_CONFIRM: 'CLOSE_ASSOCIATION_TYPES_DELETE_CONFIRM',

    OPEN_ASSOCIATION_TYPES_ROLES_MODAL_REQUEST:'OPEN_ASSOCIATION_TYPES_ROLES_MODAL_REQUEST',
    CLOSE_ASSOCIATION_TYPES_ROLES_MODAL_REQUEST:'CLOSE_ASSOCIATION_TYPES_ROLES_MODAL_REQUEST',


    ADD_ASSOCIATION_TYPES_REQUEST: 'ADD_ASSOCIATION_TYPES_REQUEST',
    REMOVE_ASSOCIATION_TYPES_REQUEST: 'REMOVE_ASSOCIATION_TYPES_REQUEST',

    CLOSE_OPERATION_SUCCESS_MODAL: 'CLOSE_OPERATION_SUCCESS_MODAL',
    CLOSE_OPERATION_FAILED_MODAL: 'CLOSE_OPERATION_FAILED_MODAL',

    CLEAR_ASSOCIATION_TYPE: 'CLEAR_ASSOCIATION_TYPE'
};

export * from './associationTypeConstants'