export const effortTypeConstants = {

    UPDATE_EFFORT_TYPE_MODAL_FIELDS: 'UPDATE_EFFORT_TYPE_FIELDS',

    CREATE_EFFORT_TYPE_REQUEST:'CREATE_EFFORT_TYPE_REQUEST',
    CREATE_EFFORT_TYPE_SUCCESS: 'CREATE_EFFORT_TYPE_SUCCESS',
    CREATE_EFFORT_TYPE_FAILURE:'CREATE_EFFORT_TYPE_FAILURE',

    SAVE_ALL_EFFORT_TYPE_REQUEST: 'SAVE_ALL_EFFORT_TYPE_REQUEST',
    SAVE_ALL_EFFORT_TYPE_SUCCESS: 'SAVE_ALL_EFFORT_TYPE_SUCCESS',
    SAVE_ALL_EFFORT_TYPE_FAILURE: 'SAVE_ALL_EFFORT_TYPE_FAILURE',

    DELETE_EFFORT_TYPE_REQUEST: 'DELETE_EFFORT_TYPE_REQUEST',
    DELETE_EFFORT_TYPE_SUCCESS: 'DELETE_EFFORT_TYPE_SUCCESS',
    DELETE_EFFORT_TYPE_FAILURE: 'DELETE_EFFORT_TYPE_FAILURE',

    UPDATE_EFFORT_TYPE_REQUEST: 'UPDATE_EFFORT_TYPE_REQUEST',
    UPDATE_EFFORT_TYPE_SUCCESS: 'UPDATE_EFFORT_TYPE_SUCCESS',
    UPDATE_EFFORT_TYPE_FAILURE: 'UPDATE_EFFORT_TYPE_FAILURE',

    GET_EFFORT_TYPE_BY_ID_REQUEST: 'GET_EFFORT_TYPE_BY_ID_REQUEST',
    GET_EFFORT_TYPE_BY_ID_SUCCESS: 'GET_EFFORT_TYPE_BY_ID_SUCCESS',
    GET_EFFORT_TYPE_BY_ID_FAILURE: 'GET_EFFORT_TYPE_BY_ID_FAILURE',

    GET_ALL_EFFORT_TYPES_REQUEST: 'GET_ALL_EFFORT_TYPES_REQUEST',
    GET_ALL_EFFORT_TYPES_SUCCESS: 'GET_ALL_EFFORT_TYPES_SUCCESS',
    GET_ALL_EFFORT_TYPES_FAILURE:  'GET_ALL_EFFORT_TYPES_FAILURE',

    OPEN_EFFORT_TYPE_MODAL_REQUEST: 'OPEN_EFFORT_TYPE_MODAL_REQUEST',
    CLOSE_EFFORT_TYPE_MODAL_REQUEST: 'CLOSE_EFFORT_TYPE_MODAL_REQUEST',

    CLOSE_EFFORT_TYPES_DELETE_CONFIRM: 'CLOSE_EFFORT_TYPES_DELETE_CONFIRM',
    OPEN_EFFORT_TYPES_DELETE_CONFIRM: 'OPEN_EFFORT_TYPES_DELETE_CONFIRM',

    CLOSE_OPERATION_SUCCESS_MODAL: 'CLOSE_OPERATION_SUCCESS_MODAL',
    CLOSE_OPERATION_FAILED_MODAL: 'CLOSE_OPERATION_FAILED_MODAL',

    CLEAR_EFFORT_TYPE:'CLEAR_EFFORT_TYPE',

    ADD_EFFORT_TYPE_REQUEST: 'ADD_EFFORT_TYPE_REQUEST',
    REMOVE_EFFORT_TYPE_REQUEST: 'REMOVE_EFFORT_TYPE_REQUEST',



};

export * from './effortTypeConstants'