export const linkedTopicConstants = {
    SAVE_LINKED_TOPICS_REQUEST: "SAVE_LINKED_TOPICS_REQUEST",
    SAVE_LINKED_TOPICS_SUCCESS: "SAVE_LINKED_TOPICS_SUCCESS",
    SAVE_LINKED_TOPICS_FAILURE: "SAVE_LINKED_TOPICS_FAILURE",

    SAVE_ALL_LINKED_TOPICS_REQUEST: "SAVE_ALL_LINKED_TOPICS_REQUEST",
    SAVE_ALL_LINKED_TOPICS_SUCCESS: "SAVE_ALL_LINKED_TOPICS_SUCCESS",
    SAVE_ALL_LINKED_TOPICS_FAILURE: "SAVE_ALL_LINKED_TOPICS_FAILURE"
};