export const occurrenceConstants = {

    GET_ALL_OCCURRENCES_REQUEST: 'GET_ALL_OCCURRENCES_OF_TOPIC_REQUEST',
    GET_ALL_OCCURRENCES_SUCCESS: 'GET_ALL_OCCURRENCES_OF_TOPIC_SUCCESS',
    GET_ALL_OCCURRENCES_FAILURE: 'GET_ALL_OCCURRENCES_OF_TOPIC_FAILURE',

    CREATE_OCCURRENCE_REQUEST: 'CREATE_OCCURRENCE_REQUEST',
    CREATE_OCCURRENCE_SUCCESS: 'CREATE_OCCURRENCE_SUCCESS',
    CREATE_OCCURRENCE_FAILURE: 'CREATE_OCCURRENCE_FAILURE',

    SAVE_ALL_OCCURRENCES_REQUEST: 'SAVE_ALL_OCCURRENCES_REQUEST',
    SAVE_ALL_OCCURRENCES_SUCCESS: 'SAVE_ALL_OCCURRENCES_SUCCESS',
    SAVE_ALL_OCCURRENCES_FAILURE: 'SAVE_ALL_OCCURRENCES_FAILURE',

    SAVE_OCCURRENCE_REQUEST: 'SAVE_OCCURRENCE_REQUEST',
    SAVE_OCCURRENCE_SUCCESS: 'SAVE_OCCURRENCE_SUCCESS',
    SAVE_OCCURRENCE_FAILURE: 'SAVE_OCCURRENCE_FAILURE',

    DELETE_OCCURRENCE_REQUEST: 'DELETE_OCCURRENCE_REQUEST',
    DELETE_OCCURRENCE_SUCCESS: 'DELETE_OCCURRENCE_SUCCESS',
    DELETE_OCCURRENCE_FAILURE: 'DELETE_OCCURRENCE_FAILURE',

    UPDATE_OCCURRENCE_REQUEST: 'UPDATE_OCCURRENCE_REQUEST',
    UPDATE_OCCURRENCE_SUCCESS: 'UPDATE_OCCURRENCE_SUCCESS',
    UPDATE_OCCURRENCE_FAILURE: 'UPDATE_OCCURRENCE_FAILURE',

    ADD_OCCURRENCE_REQUEST: 'ADD_OCCURRENCE_REQUEST',
    REMOVE_OCCURRENCE_REQUEST: 'REMOVE_OCCURRENCE_REQUEST',

    ADD_SCOPED_CONTENT: 'ADD_SCOPED_CONTENT_TO_OCCURRENCE',
    REMOVE_SCOPED_CONTENT: 'REMOVE_SCOPED_CONTENT_TO_OCCURRENCE',

    UPDATE_SCOPED_OCCURRENCE: 'UPDATE_SCOPED_OCCURRENCE',
    DELETE_SCOPED_OCCURRENCE: 'DELETE_SCOPED_OCCURRENCE',
    UPDATE_ID_OF_SCOPED_OCCURRENCE: 'UPDATE_ID_OF_SCOPED_OCCURRENCE',

    OPEN_OCCURRENCE_DELETE_CONFIRM: 'OPEN_OCCURRENCE_DELETE_CONFIRM',
    CLOSE_OCCURRENCE_DELETE_CONFIRM: 'CLOSE_OCCURRENCE_DELETE_CONFIRM',

    OPEN_ALL_OCCURRENCE_DELETE_CONFIRM: 'OPEN_ALL_OCCURRENCE_DELETE_CONFIRM',
    CLOSE_ALL_OCCURRENCE_DELETE_CONFIRM: 'CLOSE_ALL_OCCURRENCE_DELETE_CONFIRM',

    CLOSE_OPERATION_SUCCESS_MODAL: 'CLOSE_OPERATION_SUCCESS_MODAL',
    CLOSE_OPERATION_FAILED_MODAL: 'CLOSE_OPERATION_FAILED_MODAL',

    UPDATE_OCCURRENCE_FIELD: 'UPDATE_OCCURRENCE_FIELD',
    REMOVE_FILE: 'REMOVE_FILE_FROM_OCCURRENCE'

};

export * from './occurrenceConstants'
