export const topicMapConstants = {
    GET_ALL_TOPIC_MAPS_REQUEST: 'GET_ALL_USER_TOPIC_MAPS_REQUEST',
    GET_ALL_TOPIC_MAPS_SUCCESS: 'GET_ALL_USER_TOPIC_MAPS_SUCCESS',
    GET_ALL_TOPIC_MAPS_FAILURE: 'GET_ALL_USER_TOPIC_MAPS_FAILURE',

    GET_TOPIC_MAP_REQUEST: 'GET_TOPIC_MAP_REQUEST',
    GET_TOPIC_MAP_SUCCESS: 'GET_TOPIC_MAP_SUCCESS',
    GET_TOPIC_MAP_FAILURE: 'GET_TOPIC_MAP_FAILURE',

    CREATE_TOPIC_MAP_REQUEST: 'CREATE_TOPIC_MAP_REQUEST',
    CREATE_TOPIC_MAP_SUCCESS: 'CREATE_TOPIC_MAP_SUCCESS',
    CREATE_TOPIC_MAP_FAILURE: 'CREATE_TOPIC_MAP_FAILURE',

    UPDATE_TOPIC_MAP_REQUEST: 'CREATE_TOPIC_MAP_REQUEST',
    UPDATE_TOPIC_MAP_SUCCESS: 'UPDATE_TOPIC_MAP_SUCCESS',
    UPDATE_TOPIC_MAP_FAILURE: 'UPDATE_TOPIC_MAP_FAILURE',

    DELETE_TOPIC_MAP_REQUEST: 'DELETE_TOPIC_MAP_REQUEST',
    DELETE_TOPIC_MAP_SUCCESS: 'DELETE_TOPIC_MAP_SUCCESS',
    DELETE_TOPIC_MAP_FAILURE: 'DELETE_TOPIC_MAP_FAILURE',

    OPEN_TOPIC_MAP_DETAILS_MODAL_REQUEST: 'OPEN_TOPIC_MAP_DETAILS_MODAL_REQUEST',
    CLOSE_TOPIC_MAP_DETAILS_MODAL_REQUEST: 'CLOSE_TOPIC_MAP_DETAILS_MODAL_REQUEST',

    OPEN_TOPIC_MAP_CREATE_MODAL_REQUEST: 'OPEN_TOPIC_MAP_CREATE_MODAL_REQUEST',
    CLOSE_TOPIC_MAP_CREATE_MODAL_REQUEST: 'CLOSE_TOPIC_MAP_CREATE_MODAL_REQUEST',

    OPEN_TOPIC_MAP_DELETE_MODAL_REQUEST: 'OPEN_TOPIC_MAP_DELETE_MODAL_REQUEST',
    CLOSE_TOPIC_MAP_DELETE_MODAL_REQUEST: 'CLOSE_TOPIC_MAP_DELETE_MODAL_REQUEST',

    CLOSE_OPERATION_SUCCESS_MODAL: 'CLOSE_OPERATION_SUCCESS_MODAL',
    CLOSE_OPERATION_FAILED_MODAL: 'CLOSE_OPERATION_FAILED_MODAL',

    UPDATE_TOPIC_MAP_MODAL_FIELDS: 'UPDATE_TOPIC_MAP_MODAL_FIELDS',
    SELECT_TOPIC_MAP: 'SELECT_TOPIC_MAP',
    DESELECT_TOPIC_MAP: 'DESELECT_TOPIC_MAP',
    UPDATE_SELECTED_TOPIC_MAP_REQUEST: 'UPDATE_SELECTED_TOPIC_MAP_REQUEST',
    UPDATE_SELECTED_TOPIC_MAP_SUCCESS: 'UPDATE_SELECTED_TOPIC_MAP_SUCCESS',
    UPDATE_SELECTED_TOPIC_MAP_FAILURE: 'UPDATE_SELECTED_TOPIC_MAP_FAILURE'
};

export  * from './topicmapConstants'