export const topicConstants = {
    CREATE_TOPIC_REQUEST: 'CREATE_TOPIC_REQUEST',
    CREATE_TOPIC_SUCCESS: 'CREATE_TOPIC_SUCCESS',
    CREATE_TOPIC_FAILURE: 'CREATE_TOPIC_FAILURE',

    UPDATE_TOPIC_REQUEST: 'UPDATE_TOPIC_REQUEST',
    UPDATE_TOPIC_SUCCESS: 'UPDATE_TOPIC_SUCCESS',
    UPDATE_TOPIC_FAILURE: 'UPDATE_TOPIC_FAILURE',

    DELETE_TOPIC_REQUEST: 'DELETE_TOPIC_REQUEST',
    DELETE_TOPIC_SUCCESS: 'DELETE_TOPIC_SUCCESS',
    DELETE_TOPIC_FAILURE: 'DELETE_TOPIC_FAILURE',

    DELETE_TOPIC_LIST_REQUEST: 'DELETE_TOPIC_LIST_REQUEST',
    DELETE_TOPIC_LIST_SUCCESS: 'DELETE_TOPIC_LIST_SUCCESS',
    DELETE_TOPIC_LIST_FAILURE: 'DELETE_TOPIC_LIST_FAILURE',

    UPDATE_TOPIC_MODAL_FIELDS: 'UPDATE_TOPIC_MODAL_FIELDS',
    UPDATE_TOPIC_LINKS_IN_FIELDS: 'UPDATE_TOPIC_LINKS_IN_FIELDS',
    UPDATE_TOPIC_LINKS_OUT_FIELDS: 'UPDATE_TOPIC_LINKS_OUT_FIELDS',
    UPDATE_TOPICS_TO_DELETE_LIST: 'UPDATE_TOPICS_TO_DELETE_LIST',

    OPEN_TOPIC_CREATE_MODAL_REQUEST: 'OPEN_TOPIC_CREATE_MODAL_REQUEST',
    CLOSE_TOPIC_CREATE_MODAL_REQUEST: 'CLOSE_TOPIC_CREATE_MODAL_REQUEST',
    OPEN_TOPIC_DELETE_MODAL_REQUEST: 'OPEN_TOPIC_DELETE_MODAL_REQUEST',
    CLOSE_TOPIC_DELETE_MODAL_REQUEST: 'CLOSE_TOPIC_DELETE_MODAL_REQUEST',

    CLOSE_OPERATION_SUCCESS_MODAL: 'CLOSE_OPERATION_SUCCESS_MODAL',
    CLOSE_OPERATION_FAILED_MODAL: 'CLOSE_OPERATION_FAILED_MODAL',

    GET_TOPIC_REQUEST: 'GET_TOPIC_REQUEST',
    GET_TOPIC_SUCCESS: 'GET_TOPIC_SUCCESS',
    GET_TOPIC_FAILURE: 'GET_TOPIC_FAILURE',

    CLEAR_TOPIC: 'CLEAR_TOPIC'
};

export * from './topicConstants'