export const topicTypeConstants = {
    GET_ALL_TOPIC_TYPES_REQUEST: "GET_ALL_TOPIC_TYPES_REQUEST",
    GET_ALL_TOPIC_TYPES_SUCCESS: "GET_ALL_TOPIC_TYPES_SUCCESS",
    GET_ALL_TOPIC_TYPES_FAILURE: "GET_ALL_TOPIC_TYPES_FAILURE",

    CREATE_TOPIC_TYPES_REQUEST: "CREATE_TOPIC_TYPES_REQUEST",
    CREATE_TOPIC_TYPES_SUCCESS: "CREATE_TOPIC_TYPES_SUCCESS",
    CREATE_TOPIC_TYPES_FAILURE: "CREATE_TOPIC_TYPES_FAILURE",

    SAVE_ALL_TOPIC_TYPE_REQUEST: 'SAVE_ALL_TOPIC_TYPE_REQUEST',
    SAVE_ALL_TOPIC_TYPE_SUCCESS: 'SAVE_ALL_TOPIC_TYPE_SUCCESS',
    SAVE_ALL_TOPIC_TYPE_FAILURE: 'SAVE_ALL_TOPIC_TYPE_FAILURE',

    DELETE_TOPIC_TYPES_REQUEST: "DELETE_TOPIC_TYPES_REQUEST",
    DELETE_TOPIC_TYPES_SUCCESS: "DELETE_TOPIC_TYPES_SUCCESS",
    DELETE_TOPIC_TYPES_FAILURE: "DELETE_TOPIC_TYPES_FAILURE",

    UPDATE_TOPIC_TYPES_REQUEST: "UPDATE_TOPIC_TYPES_REQUEST",
    UPDATE_TOPIC_TYPES_SUCCESS: "UPDATE_TOPIC_TYPES_SUCCESS",
    UPDATE_TOPIC_TYPES_FAILURE: "UPDATE_TOPIC_TYPES_FAILURE",

    UPDATE_TOPIC_TYPE_REQUEST: "UPDATE_TOPIC_TYPE_REQUEST",
    UPDATE_TOPIC_TYPE_SUCCESS: "UPDATE_TOPIC_TYPE_SUCCESS",
    UPDATE_TOPIC_TYPE_FAILURE: "UPDATE_TOPIC_TYPE_FAILURE",

    GET_TOPIC_TYPE_BY_ID_REQUEST:"GET_TOPIC_TYPE_BY_ID_REQUEST",
    GET_TOPIC_TYPE_BY_ID_SUCCESS:"GET_TOPIC_TYPE_BY_ID_SUCCESS",
    GET_TOPIC_TYPE_BY_ID_FAILURE:"GET_TOPIC_TYPE_BY_ID_FAILURE",

    UPDATE_TOPIC_TYPE_FIELD : 'UPDATE_TOPIC_TYPE_FIELD',

    OPEN_TOPIC_TYPES_MODAL_REQUEST: 'OPEN_TOPIC_TYPES_MODAL_REQUEST',
    CLOSE_TOPIC_TYPES_MODAL_REQUEST: 'CLOSE_TOPIC_TYPES_MODAL_REQUEST',

    ADD_TOPIC_TYPES_REQUEST: 'ADD_TOPIC_TYPES_REQUEST',
    REMOVE_TOPIC_TYPES_REQUEST: 'REMOVE_TOPIC_TYPES_REQUEST',

    CLOSE_TOPIC_TYPES_DELETE_CONFIRM: 'CLOSE_TOPIC_TYPES_DELETE_CONFIRM',
    OPEN_TOPIC_TYPES_DELETE_CONFIRM: 'OPEN_TOPIC_TYPES_DELETE_CONFIRM',

    CLOSE_OPERATION_SUCCESS_MODAL: 'CLOSE_OPERATION_SUCCESS_MODAL',
    CLOSE_OPERATION_FAILED_MODAL: 'CLOSE_OPERATION_FAILED_MODAL',

    CLEAR_NOT_SAVED_TOPIC_TYPES: 'CLEAR_NOT_SAVED_TOPIC_TYPES'
};

export * from './topicTypeConstants'