export const occurrenceTypeConstants = {

    GET_ALL_OCCURRENCE_TYPE_REQUEST: 'GET_ALL_OCCURRENCE_TYPE_REQUEST',
    GET_ALL_OCCURRENCE_TYPE_SUCCESS: 'GET_ALL_OCCURRENCE_TYPE_SUCCESS',
    GET_ALL_OCCURRENCE_TYPE_FAILURE: 'GET_ALL_OCCURRENCE_TYPE_FAILURE',

    CREATE_OCCURRENCE_TYPE_REQUEST: 'CREATE_OCCURRENCE_TYPE_REQUEST',
    CREATE_OCCURRENCE_TYPE_SUCCESS: 'CREATE_OCCURRENCE_TYPE_SUCCESS',
    CREATE_OCCURRENCE_TYPE_FAILURE: 'CREATE_OCCURRENCE_TYPE_FAILURE',

    SAVE_ALL_OCCURRENCE_TYPE_REQUEST: 'SAVE_ALL_OCCURRENCE_TYPE_REQUEST',
    SAVE_ALL_OCCURRENCE_TYPE_SUCCESS: 'SAVE_ALL_OCCURRENCE_TYPE_SUCCESS',
    SAVE_ALL_OCCURRENCE_TYPE_FAILURE: 'SAVE_ALL_OCCURRENCE_TYPE_FAILURE',

    DELETE_OCCURRENCE_TYPE_REQUEST: 'DELETE_OCCURRENCE_TYPE_REQUEST',
    DELETE_OCCURRENCE_TYPE_SUCCESS: 'DELETE_OCCURRENCE_TYPE_SUCCESS',
    DELETE_OCCURRENCE_TYPE_FAILURE: 'DELETE_OCCURRENCE_TYPE_FAILURE',

    UPDATE_OCCURRENCE_TYPE_REQUEST: 'UPDATE_OCCURRENCE_TYPE_REQUEST',
    UPDATE_OCCURRENCE_TYPE_SUCCESS: 'UPDATE_OCCURRENCE_TYPE_SUCCESS',
    UPDATE_OCCURRENCE_TYPE_FAILURE: 'UPDATE_OCCURRENCE_TYPE_FAILURE',

    UPDATE_OCCURRENCE_TYPE_FIELD: 'UPDATE_OCCURRENCE_TYPE_FIELD',

    ADD_OCCURRENCE_TYPE_REQUEST: 'ADD_OCCURRENCE_TYPE_REQUEST',
    REMOVE_OCCURRENCE_TYPE_REQUEST: 'REMOVE_OCCURRENCE_TYPE_REQUEST',

    OPEN_OCCURRENCE_TYPE_MODAL_REQUEST: 'OPEN_OCCURRENCE_TYPE_MODAL_REQUEST',
    CLOSE_OCCURRENCE_TYPE_MODAL_REQUEST: 'CLOSE_OCCURRENCE_TYPE_MODAL_REQUEST',

    CLOSE_OCCURRENCE_TYPES_DELETE_CONFIRM: 'CLOSE_OCCURRENCE_TYPES_DELETE_CONFIRM',
    OPEN_OCCURRENCE_TYPES_DELETE_CONFIRM: 'OPEN_OCCURRENCE_TYPES_DELETE_CONFIRM',

    CLOSE_OPERATION_SUCCESS_MODAL: 'CLOSE_OPERATION_SUCCESS_MODAL',
    CLOSE_OPERATION_FAILED_MODAL: 'CLOSE_OPERATION_FAILED_MODAL',
};

export * from './occurrenceTypeConstants'