export const schemaConstants = {
    GET_ALL_SCHEMAS_REQUEST: 'GET_ALL_USER_SCHEMAS_REQUEST',
    GET_ALL_SCHEMAS_SUCCESS: 'GET_ALL_USER_SCHEMAS_SUCCESS',
    GET_ALL_SCHEMAS_FAILURE: 'GET_ALL_USER_SCHEMAS_FAILURE',

    GET_SCHEMA_REQUEST: 'GET_SCHEMA_REQUEST',
    GET_SCHEMA_SUCCESS: 'GET_SCHEMA_SUCCESS',
    GET_SCHEMA_FAILURE: 'GET_SCHEMA_FAILURE',

    CREATE_SCHEMA_REQUEST: 'CREATE_SCHEMA_REQUEST',
    CREATE_SCHEMA_SUCCESS: 'CREATE_SCHEMA_SUCCESS',
    CREATE_SCHEMA_FAILURE: 'CREATE_SCHEMA_FAILURE',

    UPDATE_SCHEMA_REQUEST: 'CREATE_SCHEMA_REQUEST',
    UPDATE_SCHEMA_SUCCESS: 'UPDATE_SCHEMA_SUCCESS',
    UPDATE_SCHEMA_FAILURE: 'UPDATE_SCHEMA_FAILURE',

    DELETE_SCHEMA_REQUEST: 'DELETE_SCHEMA_REQUEST',
    DELETE_SCHEMA_SUCCESS: 'DELETE_SCHEMA_SUCCESS',
    DELETE_SCHEMA_FAILURE: 'DELETE_SCHEMA_FAILURE',

    OPEN_SCHEMA_DETAILS_MODAL_REQUEST: 'OPEN_SCHEMA_DETAILS_MODAL_REQUEST',
    CLOSE_SCHEMA_DETAILS_MODAL_REQUEST: 'CLOSE_SCHEMA_DETAILS_MODAL_REQUEST',

    OPEN_SCHEMA_CREATE_MODAL_REQUEST: 'OPEN_SCHEMA_CREATE_MODAL_REQUEST',
    CLOSE_SCHEMA_CREATE_MODAL_REQUEST: 'CLOSE_SCHEMA_CREATE_MODAL_REQUEST',

    OPEN_SCHEMA_DELETE_MODAL_REQUEST: 'OPEN_SCHEMA_DELETE_MODAL_REQUEST',
    CLOSE_SCHEMA_DELETE_MODAL_REQUEST: 'CLOSE_SCHEMA_DELETE_MODAL_REQUEST',

    CLOSE_OPERATION_SUCCESS_MODAL: 'CLOSE_OPERATION_SUCCESS_MODAL',
    CLOSE_OPERATION_FAILED_MODAL: 'CLOSE_OPERATION_FAILED_MODAL',

    UPDATE_SCHEMA_MODAL_FIELDS: 'UPDATE_SCHEMA_MODAL_FIELDS',
    SELECT_SCHEMA: 'SELECT_SCHEMA',
    UPDATE_SELECTED_SCHEMA_REQUEST: 'UPDATE_SELECTED_SCHEMA_REQUEST',
    UPDATE_SELECTED_SCHEMA_SUCCESS: 'UPDATE_SELECTED_SCHEMA_SUCCESS',
    UPDATE_SELECTED_SCHEMA_FAILURE: 'UPDATE_SELECTED_SCHEMA_FAILURE'
};

export  * from './schemaConstants'