export const scopeConstants = {
    GET_ALL_SCOPES_REQUEST: 'GET_ALL_SCOPES_REQUEST',
    GET_ALL_SCOPES_SUCCESS: 'GET_ALL_SCOPES_SUCCESS',
    GET_ALL_SCOPES_FAILURE: 'GET_ALL_SCOPES_FAILURE',

    CREATE_SCOPE_REQUEST: 'CREATE_SCOPE_REQUEST',
    CREATE_SCOPE_SUCCESS: 'CREATE_SCOPE_SUCCESS',
    CREATE_SCOPE_FAILURE: 'CREATE_SCOPE_FAILURE',

    SAVE_ALL_SCOPES_REQUEST: 'SAVE_ALL_SCOPES_REQUEST',
    SAVE_ALL_SCOPES_SUCCESS: 'SAVE_ALL_SCOPES_SUCCESS',
    SAVE_ALL_SCOPES_FAILURE: 'SAVE_ALL_SCOPES_FAILURE',

    SAVE_SCOPE_REQUEST: 'SAVE_SCOPE_REQUEST',
    SAVE_SCOPE_SUCCESS: 'SAVE_SCOPE_SUCCESS',
    SAVE_SCOPE_FAILURE: 'SAVE_SCOPE_FAILURE',

    DELETE_SCOPE_REQUEST: 'DELETE_SCOPE_REQUEST',
    DELETE_SCOPE_SUCCESS: 'DELETE_SCOPE_SUCCESS',
    DELETE_SCOPE_FAILURE: 'DELETE_SCOPE_FAILURE',

    UPDATE_SCOPE_REQUEST: 'UPDATE_SCOPE_REQUEST',
    UPDATE_SCOPE_SUCCESS: 'UPDATE_SCOPE_SUCCESS',
    UPDATE_SCOPE_FAILURE: 'UPDATE_SCOPE_FAILURE',

    ADD_SCOPE_REQUEST: 'ADD_SCOPE_REQUEST',
    REMOVE_SCOPE_REQUEST: 'REMOVE_SCOPE_REQUEST',

    OPEN_SCOPE_DELETE_CONFIRM: 'OPEN_SCOPE_DELETE_CONFIRM',
    CLOSE_SCOPE_DELETE_CONFIRM: 'CLOSE_SCOPE_DELETE_CONFIRM',
    UPDATE_SCOPE_FIELD: 'UPDATE_SCOPE_FIELD',

    UPDATE_SCOPE_MODAL_FIELD: 'UPDATE_SCOPE_MODAL_FIELD',

    OPEN_SCOPES_MODAL_REQUEST: 'OPEN_SCOPES_MODAL_REQUEST',
    CLOSE_SCOPES_MODAL_REQUEST: 'CLOSE_SCOPES_MODAL_REQUEST',

    CLOSE_OPERATION_SUCCESS_MODAL: 'CLOSE_OPERATION_SUCCESS_MODAL',
    CLOSE_OPERATION_FAILED_MODAL: 'CLOSE_OPERATION_FAILED_MODAL',

    CLEAR_NOT_SAVED_SCOPES: 'CLEAR_NOT_SAVED_SCOPES'
};