export const userConstants = {
    SIGN_UP_REQUEST: 'USER_SIGN_UP_REQUEST',
    SIGN_UP_SUCCESS: 'USER_SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'USER_SIGN_UP_FAILURE',

    LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

    LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'USER_LOGOUT_FAILURE',

    GET_ALL_REQUEST: 'USERS_GET_ALL_REQUEST',
    GET_ALL_SUCCESS: 'USERS_GET_ALL_SUCCESS',
    GET_ALL_FAILURE: 'USERS_GET_ALL_FAILURE',

    UPDATE_SIGN_UP_FIELD: 'UPDATE_SIGN_UP_FIELD',
    UPDATE_LOGIN_FIELD: 'UPDATE_SIGN_UP_FIELD',

    OPEN_SESSION_EXPIRED_MODAL: 'OPEN_SESSION_EXPIRED_MODAL',
    CLOSE_SESSION_EXPIRED_MODAL: 'CLOSE_SESSION_EXPIRED_MODAL',

    RELOAD_USER_SESSION_REQUEST: 'RELOAD_USER_SESSION_REQUEST',
    RELOAD_USER_SESSION_SUCCESS: 'RELOAD_USER_SESSION_SUCCESS',
    RELOAD_USER_SESSION_FAILURE: 'RELOAD_USER_SESSION_FAILURE',
};

export * from './userConstants'